### PR TITLE
Add French i18n

### PR DESCRIPTION
**Pull request by don-vip**

### CODE REVIEW

**Comment by don-vip** [comment]
There is no instruction in the file. Do the ITW rules apply?
```
# Apostrophe characters ' need to be escaped by using two: ''
# Curly brackets need to be escaped by surrounding them with single apostrophes '{' '{hello}'
```

**Comment by AndreasEhret** [comment]
yes, same rules apply. We will improve instructions in OpenWebStart bundle files accordingly.

**Comment by don-vip** [comment]
Why is the PR closed? I didn't escape the apostrophes yet.

**Comment by AndreasEhret** [comment]
sorry, I was too fast on that...

**Comment by don-vip** [comment]
@AndreasEhret it's done, the PR is up for review.

**Comment by hendrikebbers** [comment]
@don-vip we really like your PR and would love to merge it. We just have 1 problem here: Since OWS is still in development some of the text will change in future and new texts will be added. Can you help us here? We do not want to provide a 90% translated French version in future. If you are ok with taking care of that in the future we will merge this PR :)

**Comment by don-vip** [comment]
> some of the text will change in future and new texts will be added. Can you help us here? We do not want to provide a 90% translated French version in future. If you are ok with taking care of that in the future we will merge this PR :)

No problem, count me in! Can you please just let me know when new strings are added? I don't follow OWS development actively.

**Pull request merged**
