### PR TITLE
Adding .editorconfig file

### PR DESCRIPTION
**Pull request by sonechca**
I added a new file ".editorconfig" for issue 302.
I focused on Java files and if I need to fix or add more, let me know by commenting here
This is my first time creating a .editorconfig file. But I want to finish this issue by myself
So you can give me any advice or tips as well, Thank you so much
Have a good Thanksgiving day

### CODE REVIEW

**Comment by sclassen** [comment]
Wow this was super fast.
Please give us some time with this to review. My experience is that code formatting almost always leads to larger discussions.
So far we have not tried to decide on a common style for this project. Your PR will spark this discussion now.

Thank you for your contribution and sorry if this will take some time to get reviewed.

**Comment by sclassen** [comment]
@cla-bot check

**Comment by hendrikebbers** [comment]
@sonechca can you please sign our CLA? Otherwise we can not merge this PR :(

**Comment by sclassen** [comment]
@sonechca Can you please sign the CLA so we can get this in as part of the Hacktober

**Comment by sclassen** [comment]
fixed with #347

**Pull request closed without merging**
