### PR TITLE
GitHub issue #464

### PR DESCRIPTION
**Pull request by acsipak**
See https://github.com/karakun/OpenWebStart/issues/464

The first commit implements a simple Java application emulating the java executable nonstandard option -XshowSettings:properties (which was introduced in Java SE 1.8).

Notice the Maven source and target levels in the new module's POM are set to 1.6 . (With further code modifications, it's possible set it to older versions, if we aim to be backwards compatible with older JVMs.)

The mini application currently emulates "java -XshowSettings:properties -version", but it's possible to make it even simpler to only output the 4 properties JavaRuntimePropertiesDetector needs.

The second commit affects JavaRuntimePropertiesDetector, so that if "java -XshowSettings:properties -version" fails for any reason, it falls back to using the SystemPropertiesPrinter executable.

I could not figure out how exactly you package OWS (except for the hint that you probably use install4j). So I assumed SystemPropertiesPrinter resides in the OWS installdir adjacent to openwebstart.jar 

The sppJarPath() method feels somewhat clumsy. (I tried to mimic some of the logic in OwsJvmLauncher.getOwsEcecutablePath().)

This is by no means the final form of the PR. I just wanted to show how I meant to fix GitHub issue #464

### CODE REVIEW

**Comment by sclassen** [comment]
Just thinking out loud:
Would it be possible to include the new SystemPropertiesPrinter as a dependency to openwebstart?
Since we are already building a fat jar with ITW and other dependencies.
The class file would still be 1.6 compatible and we would not need to package a second jar file.
Also the code for locating the jar could re-use the method OwsJvmLauncher.getOpenWebStartJar()

**Comment by acsipak** [comment]
I did as @sclassen advised, also made SystemPropertiesPrinter a bit simpler.

One small glitch is that OwsJvmLauncher.getOpenWebStartJar() won't work if I launch OWS Control Panel from IDE since normally the classpath does not contain "openwebstart.jar" in this case. I wasn't able to work around this yet.

Another thing to note is that by default OWS has a ows.jvm.manager.versionRange=1.8+ setting. If we want to test how adding an older JVM (which does not support -XshowSettings) works out, we need to override this property default.

**Comment by sclassen** [comment]
Yes you are right, running the `getOpenWebStartJar()` from within the IDE does not work. But you can assume it is correct as without this function no JNLP could be launched.
What you can do to try your code is to build the openwebstart.jar and simply replace the jar in you installation directory. Maybe keep a copy of the original to switch back later.

The `ows.jvm.manager.versionRange` can simply be added to the deployment.properties file to change its value.

But I doubt that this is sufficient as OWS is making heavy use of java features which have only been added in 1.8 (like lambdas and streams). So my assumption is that if you use your code to add a JVM 1.6 this will work fine. But when you then tell OWS to launch a JNLP with the 1.6 JVM this will fail. As OWS puts the openwebstart.jar on the boot classpath of the instance of the the 1.6 JVM and runs a lot of code before the actual application is started. All that code is compiled agains Java 8 and thus will not run on the 1.6 VM

**Comment by acsipak** [comment]
I was able to do a test as suggested (replacing openwebstart.jar and adding ows.jvm.manager.versionRange=1.6+ to deployment.properties). I was succesfully able to add an Oracle 1.7.0_80 JRE to the JVM list in OWS Control Panel. Oracle JVM supports the -XshowSettings since 1.8.0, so this time we had to fall back to running SystemPropertiesPrinter and it worked as expected.

Do you require any further modifications to the PR?

Side story: launching a JNLP with the 1.7.0 JVM failed as you predicted, even after I disabled the hardcoded version check in OwsJvmLauncher.launchExternal(). The stage1 log did not give much details about how and why the launch failed: only INFO and DEBUG entries were logged. But the log entry "About to launch external with commands:" provided some information about the exact command OWS used to fire up the application. Running the command in cmd.exe resulted in the following exception:

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/sourceforge/jnlp/runtime/Boot : Unsupported major.minor version 52.0

**Comment by sclassen** [comment]
Regarding the PR: Will have a look at it this week and come back to you if there is anything which needs changing

Regarding the Unsuported major.minor version: This is the behavior I was expecting as the JVM 1.7 cannot run the OWS code which is for a JVM 1.8.
You would need to compile both the icedtea-web and the openwebstart compatible to a 1.7 JVM. But this will not be easy as the code is using features introduced in 1.8 (such as streams and lambdas).

**Pull request merged**
