### PR TITLE
Doc javaws cmdline args

### PR DESCRIPTION
**Pull request by janakmulani**

### CODE REVIEW

**Comment by sclassen** [comment]
@AndreasEhret @hendrikebbers 
Can one of you test the documented features on Mac. If I remember correctly MacOS is different when it comes to starting OWS from the console.

**Comment by AndreasEhret** [comment]
the command on Mac uses open: open /Applications/OpenWebStart/OpenWebStart\ javaws.app myApp.jnlp --args -Xoffline

I will add some notes accordingly to the PR.

**Comment by mst-ableton** [comment]
Hey there! Thank you for OpenWebStart!

I hope I'm not unwelcome in jumping into this PR. I've been recently experimenting with OWS on MacOS and the command line that @AndreasEhret posted is partially, but not fully, correct. The `-a` option to `open` must be used to instruct `open` to open the file or URL with the selected command. Otherwise, `open` is running two open commands, one for the application (which will harmlessly load and exit) and one for the JNLP file or URL (which will open if the handler is registered properly, but will fail if not). The "proper" command on MacOS should be something like

```sh
open -a "OpenWebStart javaws" myApp.jnlp
```
or
```sh
open -a "OpenWebStart javaws" https://my.example.url/myApp.jnlp
```

Args can be provided as well:

```sh
open -a "OpenWebStart javaws" myApp.jnlp --args -Xoffline
```

I believe it's also possible to use `open`'s `-b` "bundle identifier" option to be more precise, but `-a` was sufficient for my purposes.

However, some applications rely on calling the ` javaws` executable directly. Since the JNLP file or URL comes at the end of that invocation, using it with `open` requires some argument wrangling. I've made the following shell script to do that, it's a bit complicated but it seems to do the shell escaping correctly (and `shellcheck` is happy with it):

```sh
#!/bin/bash
# A wrapper for OpenWebStart that behaves like 'javaws' on MacOS.

if [ "$#" -lt 1 ]; then
    echo "Must provide at least a JNLP file or URL"
    exit 1
fi

# The JNLP file or URL which much be at the end of the argument list.
jnlp=${!#}

# The rest of the arguments, if there are any.
argarray=("${@:1:$#-1}")

open -a "OpenWebStart javaws" "$jnlp" --args "${argarray[@]}"
```

Saving this to `/usr/local/bin/javaws` and running `chmod +x` on it makes it work.

I'd like to make a feature request to have a proper `javaws` executable with the MacOS distribution, but this workaround should hopefully suffice if that's somehow not desirable or possible. Thanks!

**Comment by sclassen** [comment]
Also inviting @hendrikebbers to participate in this PR

**Comment by AndreasEhret** [comment]
Added @mst-ableton 's -a improvements. Thanks for jumping into this PR! @hendrikebbers does this also looks reasonable for you?

**Pull request merged**
