### PR TITLE
Concurrency Enhancements

### PR DESCRIPTION
**Pull request by martinhickson**
- Added a deployment property to optionally treat the cache.json file as read-only

### CODE REVIEW

**Comment by sclassen** [comment]
The save method is also used to update the last usage of a JVM. There is a cleanup policy which will remove JVMs which have not been used for a longer period.

This must also respect the read only flag.

Also have you measured the time that is lost because of this locking? If it is only very short we tend to keep the code as it is right now.

**Comment by martinhickson** [comment]
The use-case is a multi-user system with a shared JVM cache directory that results in multiple concurrent readers and writers, which may, depending on timing result in readers reading from the file while it is being saved.  In practice, this often results in an empty cache.json file resulting in a need for reconfiguration.  The option is configurable (and non-default) as it means that JDKs won't expire when the option is enabled, but for this particular use-case there is typically only one pre-configured JDK version that almost never changes.

**Comment by drh-bravura** [comment]
[Bravura Solutions (NZ) CLA.pdf](https://github.com/karakun/OpenWebStart/files/6729710/Bravura.Solutions.NZ.CLA.pdf)

Hi
The signed corporate CLA was emailed to opensource@karakun.com on the 24'th June and is attached here. 
Whenever is convenient can we get an indication if this enhancement will be accepted please. We have a grumpy client having trouble launching an app in a shared environment.
Many thanks.

**Comment by sclassen** [comment]
@cla-bot check

**Comment by sclassen** [comment]
Fixed with #435

**Pull request closed without merging**
